import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import dbConnect from "@/lib/db";
import Claim from "@/models/Claim";
import Post from "@/models/Post";
import Reputation from "@/models/Reputation";
import { verifyHandoffCode } from "@/lib/handoff";

// Confirm Code (Claimant)
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || !session.user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }
        // @ts-ignore
        const userId = session.user.id;
        const { id } = await params;

        // Can be entered by claimant (normally) or finder (if they are doing it together)?
        // Usually claimant enters code given by finder?
        // OR Finder enters code given by Claimant?
        // "Handoff code: numeric... Show code only inside verified thread" usually implied ONE party generates, OTHER verifies.
        // Let's assume Finder generates, Claimant enters to prove receipt? 
        // OR Claimant generates "Pickup Code", Finder scans/enters it. 
        // Let's go with: Finder generates code (as per previous file), Claimant enters it? 
        // Actually, usually "Pickup Code" is generated by the RECIPIENT (Claimant) and given to the GIVER (Finder) to prove they are the right person.
        // BUT the prompt says: "POST /api/claims/:id/handoff-code -> Generate... (only finder can generate)."
        // So Finder generates code. Who confirms?
        // "POST /api/claims/:id/handoff-confirm -> Claimant enters code; verify vs hashed..."
        // OK, ensuring I follow that.

        const { code } = await req.json();

        await dbConnect();
        const claim = await Claim.findById(id).populate("post");
        if (!claim) return NextResponse.json({ error: "Not found" }, { status: 404 });

        if (claim.claimant.toString() !== userId) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

        if (!claim.handoffCodeHash) {
            return NextResponse.json({ error: "No code generated yet" }, { status: 400 });
        }

        const isValid = await verifyHandoffCode(code, claim.handoffCodeHash);
        if (!isValid) {
            return NextResponse.json({ error: "Invalid code" }, { status: 400 });
        }

        // Success! 
        claim.status = 'approved'; // Ensure it is approved? Or 'resolved'?
        // Let's accept 'approved' or update Post status to 'claimed' or 'resolved'

        // Update Post
        await Post.findByIdAndUpdate(claim.post._id, { status: 'resolved' });

        // Update Reputation (Finder + Claimant)
        // Finder gets karma
        // @ts-ignore
        await Reputation.findOneAndUpdate(
            // @ts-ignore
            { user: claim.post.user },
            { $inc: { score: 20, successfulHandoffs: 1 } },
            { upsert: true }
        );

        // Claimant gets karma
        await Reputation.findOneAndUpdate(
            { user: userId },
            { $inc: { score: 10, successfulHandoffs: 1 } },
            { upsert: true }
        );

        return NextResponse.json({ success: true });

    } catch (error) {
        console.error(error);
        return NextResponse.json({ error: "Error" }, { status: 500 });
    }
}
